-- -----------------------------------------------------------------------------
-- Cooldowns
-- Author:  g4rr3t
-- Created: Oct 6, 2018
--
-- Sounds.lua
-- -----------------------------------------------------------------------------

Cool = Cool or {}
Cool.Sounds = {
    options = {
        "ACTIVE_SKILL_MORPH_CHOSEN",
        "ABILITY_PICKED_UP",
        "SKILL_PURCHASED",
        "ABILITY_SLOTTED",
        "ABILITY_SYNERGY_READY",
        "ABILITY_ULTIMATE_READY",
        "ACHIEVEMENT_AWARDED",
        "ALCHEMY_CREATE_TOOLTIP_GLOW_SUCCESS",
        "ALLIANCE_POINT_TRANSACT",
        "AVA_GATE_CLOSED",
        "AVA_GATE_OPENED",
        "BATTLEGROUND_CAPTURE_AREA_MOVED",
        "BATTLEGROUND_CAPTURE_AREA_CAPTURED_OTHER_TEAM",
        "BATTLEGROUND_CAPTURE_AREA_CAPTURED_OWN_TEAM",
        "BATTLEGROUND_CAPTURE_AREA_SPAWNED",
        "BATTLEGROUND_CAPTURE_FLAG_CAPTURED_BY_OTHER_TEAM",
        "BATTLEGROUND_CAPTURE_FLAG_RETURNED",
        "BATTLEGROUND_MATCH_LOST",
        "BATTLEGROUND_MATCH_WON",
        "BATTLEGROUND_MURDERBALL_TAKEN_OTHER_TEAM",
        "BATTLEGROUND_MURDERBALL_TAKEN_OWN_TEAM",
        "BATTLEGROUND_MEDAL_RECEIVED",
        "BATTLEGROUND_ONE_MINUTE_WARNING",
        "BATTLEGROUND_NEARING_VICTORY",
        "BLACKSMITH_EXTRACTED_BOOSTER",
        "BLACKSMITH_IMPROVE_TOOLTIP_GLOW_SUCCESS",
        "BOOK_ACQUIRED",
        "BOOK_COLLECTION_COMPLETED",
        "CHAMPION_CYCLED_TO_MAGE",
        "CHAMPION_POINT_GAINED",
        "CHAMPION_STAR_LOCKED",
        "CHAMPION_SYSTEM_UNLOCKED",
        "CHAMPION_ZOOM_IN",
        "CHAMPION_ZOOM_OUT",
        "CLOTHIER_IMPROVE_TOOLTIP_GLOW_SUCCESS",
        "COLLECTIBLE_UNLOCKED",
        "CROWN_CRATES_CARD_FLIPPING",
        "CROWN_CRATES_GEM_ITEM",
        "CROWN_CRATES_MANIFEST_IN",
        "CROWN_CRATES_MANIFEST_SELECTED",
        "DEATH_RECAP_ATTACK_SHOWN",
        "DEATH_RECAP_KILLING_BLOW_SHOWN",
        "DIALOG_ACCEPT",
        "DIALOG_DECLINE",
        "DISPLAY_ANNOUNCEMENT",
        "DUEL_ACCEPTED",
        "DUEL_BOUNDARY_WARNING",
        "DUEL_START",
        "DUEL_WON",
        "ELDER_SCROLL_CAPTURED_BY_ALDMERI",
        "EMPEROR_ABDICATED",
        "EMPEROR_CORONATED_ALDMERI",
        "EMPEROR_DEPOSED_ALDMERI",
        "ENCHANTING_CREATE_TOOLTIP_GLOW",
        "ENLIGHTENED_STATE_GAINED",
        "ENLIGHTENED_STATE_LOST",
        "GIFT_INVENTORY_VIEW_FANFARE_SPARKS",
        "GROUP_ELECTION_REQUESTED",
        "GROUP_ELECTION_RESULT_LOST",
        "GROUP_ELECTION_RESULT_WON",
        "GUILD_ROSTER_ADDED",
        "GUILD_ROSTER_REMOVED",
        "HUD_ARMOR_BROKEN",
        "INVENTORY_ITEM_APPLY_CHARGE",
        "INVENTORY_ITEM_APPLY_ENCHANT",
        "INVENTORY_ITEM_REPAIR",
        "JUSTICE_NO_LONGER_KOS",
        "JUSTICE_NOW_KOS",
        "JUSTICE_PICKPOCKET_BONUS",
        "JUSTICE_PICKPOCKET_FAILED",
        "JUSTICE_STATE_CHANGED",
        "LEVEL_UP",
        "LEVEL_UP_REWARD_CLAIM",
        "LEVEL_UP_REWARD_FANFARE",
        "LOCKPICKING_CHAMBER_LOCKED",
        "LOCKPICKING_BREAK",
        "LOCKPICKING_SUCCESS_CELEBRATION",
        "LOCKPICKING_UNLOCKED",
        "MARKET_CROWN_GEMS_SPENT",
        "ITEM_MONEY_CHANGED",
        "OBJECTIVE_ACCEPTED",
        "OBJECTIVE_COMPLETED",
        "QUEST_ACCEPTED",
        "QUEST_COMPLETED",
        "QUEST_SHARE_SENT",
        "RAID_TRIAL_COUNTER_UPDATE",
        "RAID_TRIAL_SCORE_ADDED_VERY_HIGH",
        "RAID_TRIAL_SCORE_ADDED_LOW",
        "RAID_TRIAL_SCORE_ADDED_NORMAL",
        "RETRAITING_RETRAIT_TOOLTIP_GLOW_SUCCESS",
        "SKILL_LINE_ADDED",
        "SKILL_LINE_LEVELED_UP",
        "SKILL_XP_DARK_ANCHOR_CLOSED",
        "SKILL_POINT_GAINED",
        "STATS_PURCHASE",
        "TELVAR_GAINED",
        "TELVAR_LOST",
        "TELVAR_MULTIPLIERMAX",
        "TELVAR_MULTIPLIERUP",
        "VOICE_CHAT_ALERT_CHANNEL_MADE_ACTIVE",
        "WOODWORKER_IMPROVE_TOOLTIP_GLOW_SUCCESS",
    },
    names = {
        "Skill Morph Chosen",
        "Ability Picked Up",
        "Skill Purchased",
        "Ability Slotted",
        "Ability Synergy Ready",
        "Ability Ultimate Ready",
        "Achievement Awarded",
        "Alchemy Success",
        "Alliance Points Purchase",
        "AVA Gate Closed",
        "AVA Gate Opened",
        "BG Point Moved",
        "BG Point Enemy Capture",
        "BG Point Friendly Captured",
        "BG Point Spawned",
        "BG Relic Enemy Captured",
        "BG Relic Returned",
        "BG Lost",
        "BG Won",
        "BG Chaosball Enemy Pickup",
        "BG Chaosball Friendly pickup",
        "BG Medal Awarded",
        "BG One Minute Warning",
        "BG Nearing Victory",
        "Blacksmith Booster Received",
        "Blacksmith Success",
        "Book Acquired",
        "Book Collection Complete",
        "Champion Point Rotate",
        "Champion Point Gained",
        "Champion Point Star Unlocked",
        "Champion Point System Unlocked",
        "Champion Point Zoom In",
        "Champion Point Zoom Out",
        "Clothier Success",
        "Collectible Unlocked",
        "Crown Crate Flip Card",
        "Crown Crate Gem Item",
        "Crown Crate Manifest In",
        "Crown Crate Manifest Selected",
        "Death Recap Attack",
        "Death Recap Killing Blow",
        "Dialog Accept",
        "Dialog Decline",
        "Display Announcement",
        "Duel Accepted",
        "Duel Boundary Warning",
        "Duel Start",
        "Duel Won",
        "Elder Scroll Captured",
        "Emperor Abdicated",
        "Emperor Coronated",
        "Emperor Deposed",
        "Enchanting Success",
        "Enlightenment Gained",
        "Enlightenment Lost",
        "Gift Inventory Fanfare Sparks",
        "Group Vote Request",
        "Group Vote Failed",
        "Group Vote Passed",
        "Guild Roster Added",
        "Guild Roster Removed",
        "HUD Armor Broken",
        "Inventory Apply Charge",
        "Inventory Apply Enchant",
        "Inventory Apply Repair",
        "Justice No Longer KOS",
        "Justice KOS",
        "Pickpocket Bonus",
        "Pickpocket Failed",
        "Justice State Changed",
        "Level Up",
        "Level Up Reward Claim",
        "Level Up Reward Fanfare",
        "Lockpick Chamber Unlocked",
        "Lockpick Break",
        "Lockpick Success",
        "Lockpick Unlocked",
        "Crown Gems Spent",
        "Money Changed",
        "Objective Accepted",
        "Objective Completed",
        "Quest Accepted",
        "Quest Completed",
        "Quest Share Sent",
        "Raid Vitality Lost",
        "Raid Very High Score",
        "Raid Low Score",
        "Raid Normal Score",
        "Retrait Success",
        "Skill Line Added",
        "Skill Line Level Up",
        "Dark Anchor Closed",
        "Skill Point Gained",
        "Stats Purchase",
        "Tel Var Gained",
        "Tel Var Lost",
        "Tel Var Max Multiplier",
        "Tel Var Multiplier Increased",
        "Voice Channel Active",
        "Woodworking Success",
    },
}
